import { existsSync, readFileSync } from "node:fs";
import { builtinModules } from "node:module";
import { resolve } from "node:path";
import type { Plugin } from "vite";
import { defineConfig } from "vite";

/**
 * Load .env file without external dependencies
 * Returns an object with environment variables from .env file
 */
function loadEnvFile(): Record<string, string> {
	const envPath = resolve(process.cwd(), ".env");
	if (!existsSync(envPath)) return {};

	const env: Record<string, string> = {};
	const content = readFileSync(envPath, "utf-8");
	for (const line of content.split("\n")) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith("#")) continue;
		const [key, ...valueParts] = trimmed.split("=");
		if (key) env[key.trim()] = valueParts.join("=").trim();
	}
	return env;
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE + ROLLDOWN
if you want to view the source, please visit the github repository of this plugin
*/
`;

function bannerPlugin(): Plugin {
	return {
		name: "banner-plugin",
		generateBundle(_options, bundle) {
			for (const chunk of Object.values(bundle)) {
				if (chunk.type === "chunk") {
					chunk.code = banner + chunk.code;
				}
			}
		},
	};
}

export default defineConfig(({ mode }) => {
	const isProd = mode === "production";
	const env = loadEnvFile();
	const pluginDir = env.OBSIDIAN_PLUGIN_DIR;

	// Determine output directory:
	// - Production: always output to project root (safe for CI/CD)
	// - Development: output to vault if OBSIDIAN_PLUGIN_DIR is set, otherwise project root
	const outDir = !isProd && pluginDir ? pluginDir : ".";

	if (!isProd) {
		if (pluginDir) {
			console.log(`[dev] Output to: ${pluginDir}/main.js`);
		} else {
			console.log("[dev] OBSIDIAN_PLUGIN_DIR not set. Output to: ./main.js");
			console.log(
				"[dev] Create .env file with OBSIDIAN_PLUGIN_DIR to enable direct vault output.",
			);
		}
	}

	return {
		plugins: [bannerPlugin()],
		build: {
			outDir,
			emptyOutDir: false,
			lib: {
				entry: "src/main.ts",
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			sourcemap: isProd ? false : "inline",
			minify: isProd,
			rollupOptions: {
				external: [
					"obsidian",
					"electron",
					"@codemirror/autocomplete",
					"@codemirror/collab",
					"@codemirror/commands",
					"@codemirror/language",
					"@codemirror/lint",
					"@codemirror/search",
					"@codemirror/state",
					"@codemirror/view",
					"@lezer/common",
					"@lezer/highlight",
					"@lezer/lr",
					...builtinModules,
				],
				output: {
					entryFileNames: "main.js",
				},
			},
		},
		test: {
			globals: true,
			environment: "node",
			include: ["src/**/*.test.ts"],
			coverage: {
				provider: "v8",
				reporter: ["text", "json", "html"],
				exclude: ["node_modules/", "src/**/*.test.ts"],
			},
			server: {
				deps: {
					external: ["obsidian"],
				},
			},
		},
	};
});
